### ISSUE TITLE
error in lab-01

### ISSUE THREAD

**Issue by raomohsinkhan** [ids-s1-20/labs#8]
hi there,

while kniting lab-01-plastic-waste.Rmd

i am getting this error

error in loadNamespace(name) : there is no package called 'emo' calls:<Anonymous>....
loadNamespace 
withRestarts  withonerestart  dowwtihonerestart
execution halted

Quitting from lines 177-186 (lab-01-plastic-waste.Rmd) 
Error in loadNamespace(name) : there is no package called 'emo'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

**Comment by mine-cetinkaya-rundel** [comment]
You can install the package with `devtools::install_github("hadley/emo")` and then it should work.

**Comment by raomohsinkhan** [comment]
but you said in the video that r mark down file are completely reproducible.
you showed an example in which you assign x -> 2, in R environment the variable x has been initialized but in the rmd file the x variable is unknown.
so why devtools:: instal.....
have the issue.
anyway i dont understand. i am new in R

thank you 
rao
